### ISSUE TITLE
Bunch of failing tests on Ruby 2.3.0

### ISSUE THREAD

**Issue by henrik** [ball-hayden/uk_account_validator#2]
When I run the `cucumber` command I get 10 failed scenarios. Same for you?

**Comment by henrik** [comment]
Hm, weird. https://travis-ci.org/ball-hayden/uk_account_validator/jobs/140755214 is green.

But locally, also with commit f8398200d2328813fdca8992365c19355003ccb7, I get failures:

```
12:12:24 uk_account_validator ruby-2.3.0 master$ bundle exec cucumber
Feature: Allow hyphens in sort codes

  Background:                    # features/allow_hyphens_in_sort_codes.feature:2
    Given I create a new checker # features/step_definitions/basics.rb:1

  Scenario: A user supplies a valid sort code separated by hyphens # features/allow_hyphens_in_sort_codes.feature:5
    Given I have a sort code 08-99-99                              # features/step_definitions/basics.rb:5
    And I have an account number 66374958                          # features/step_definitions/basics.rb:9
    Then the combination is valid                                  # features/step_definitions/basics.rb:17

Feature: Exceptions

  Background:                    # features/exceptions.feature:3
    Given I create a new checker # features/step_definitions/basics.rb:1

  Scenario Outline: Valid Codes                  # features/exceptions.feature:6
    Given I have a sort code <sortcode>          # features/exceptions.feature:7
    And I have an account number <accountnumber> # features/exceptions.feature:8
    Then the combination is valid                # features/exceptions.feature:10

    Examples:
      | test | description                                                                                                      | sortcode | accountnumber |
      | 4    | Exception 10 & 11 where first check passes and second check fails.                                               | 871427   | 46238510      |
      | 5    | Exception 10 & 11 where first check fails and second check passes.                                               | 872427   | 46238510      |
      | 6    | Exception 10 where in the account number ab=09 and the g=9. The first check passes and second check fails.       | 871427   | 09123496      |
      | 7    | Exception 10 where in the account number ab=99 and the g=9. The first check passes and the second check fails.   | 871427   | 99123496      |
      | 8    | Exception 3, and the sorting code is the start of a range. As c=6 the second check should be ignored.            | 820000   | 73688637      |
      | 9    | Exception 3, and the sorting code is the end of a range. As c=9 the second check should be ignored.              | 827999   | 73988638      |
      | 10   | Exception 3. As c!=6 or 9 perform both checks pass.                                                              | 827101   | 28748352      |
      | 11   | Exception 4 where the remainder is equal to the checkdigit.                                                      | 134020   | 63849203      |
      | 12   | Exception 1 - ensures that 27 has been added to the accumulated total and passes double alternate modulus check. | 118765   | 64371389      |
      | 13   | Exception 6 where the account fails standard check but is a foreign currency account.                            | 200915   | 41011166      |
      | 14   | Exception 5 where the check passes.                                                                              | 938611   | 07806039      |
      | 15   | Exception 5 where the check passes with substitution.                                                            | 938600   | 42368003      |
      | 16   | Exception 5 where both checks produce a remainder of 0 and pass.                                                 | 938063   | 55065200      |
      | 17   | Exception 7 where passes but would fail the standard check.                                                      | 772798   | 99345694      |
      | 18   | Exception 8 where the check passes.                                                                              | 086090   | 06774744      |
      | 19   | Exception 2 & 9 where the first check passes.                                                                    | 309070   | 02355688      |
      | 20   | Exception 2 & 9 where the first check fails and second check passes with substitution.                           | 309070   | 12345668      |
      | 21   | Exception 2 & 9 where a!=0 and g!=9 and passes.                                                                  | 309070   | 12345677      |
      | 22   | Exception 2 & 9 where a!=0 and g=9 and passes.                                                                   | 309070   | 99345694      |
      | 31   | Exception 12/13 where passes modulus 11 check                                                                    | 074456   | 12345112      |
      | 32   | Exception 12/13 where passes the modulus 11 check                                                                | 070116   | 34012583      |
      | 33   | Exception 12/13 where fails the modulus 11 check, but passes the modulus 10 check.                               | 074456   | 11104102      |
      | 34   | Exception 14 where the first check fails and the second check passes.                                            | 180002   | 00000190      |

  Scenario Outline: Invalid Codes                # features/exceptions.feature:38
    Given I have a sort code <sortcode>          # features/exceptions.feature:39
    And I have an account number <accountnumber> # features/exceptions.feature:40
    Then the combination is invalid              # features/exceptions.feature:42

    Examples:
      | test | description                                                                 | sortcode | accountnumber |
      | 23   | Exception 5 where the first checkdigit is correct and the second incorrect. | 938063   | 15764273      |

      expected false
           got true
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basics.rb:22:in `/^the combination is invalid$/'
      features/exceptions.feature:46:in `Then the combination is invalid'
      features/exceptions.feature:42:in `Then the combination is invalid'
      | 24   | Exception 5 where the first checkdigit is incorrect and the second correct. | 938063   | 15764264      |

      expected false
           got true
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basics.rb:22:in `/^the combination is invalid$/'
      features/exceptions.feature:47:in `Then the combination is invalid'
      features/exceptions.feature:42:in `Then the combination is invalid'
      | 25   | Exception 5 where the first checkdigit is incorrect with a remainder of 1.  | 938063   | 15763217      |

      expected false
           got true
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basics.rb:22:in `/^the combination is invalid$/'
      features/exceptions.feature:48:in `Then the combination is invalid'
      features/exceptions.feature:42:in `Then the combination is invalid'
      | 26   | Exception 1 where it fails double alternate check.                          | 118765   | 64371388      |

      expected false
           got true
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basics.rb:22:in `/^the combination is invalid$/'
      features/exceptions.feature:49:in `Then the combination is invalid'
      features/exceptions.feature:42:in `Then the combination is invalid'

Feature: Account number and sort code must be in recognised format

  Background:                    # features/invalid_formats.feature:2
    Given I create a new checker # features/step_definitions/basics.rb:1

  Scenario: Account number contains letters # features/invalid_formats.feature:5
    Given I have a sort code 089999         # features/step_definitions/basics.rb:5
    And I have an account number abcdefgh   # features/step_definitions/basics.rb:9
    Then the combination is invalid         # features/step_definitions/basics.rb:21

  Scenario: Account number must be at least 6 digits # features/invalid_formats.feature:11
    Given I have a sort code 089999                  # features/step_definitions/basics.rb:5
    And I have an account number 66374               # features/step_definitions/basics.rb:9
    Then the combination is invalid                  # features/step_definitions/basics.rb:21

  Scenario: Account number may not be more than 10 digits # features/invalid_formats.feature:17
    Given I have a sort code 089999                       # features/step_definitions/basics.rb:5
    And I have an account number 66374958663              # features/step_definitions/basics.rb:9
    Then the combination is invalid                       # features/step_definitions/basics.rb:21

  Scenario: The sort code may not be less than 6 digits # features/invalid_formats.feature:23
    Given I have a sort code 08999                      # features/step_definitions/basics.rb:5
    And I have an account number 66374958               # features/step_definitions/basics.rb:9
    Then the combination is invalid                     # features/step_definitions/basics.rb:21

  Scenario: The sort code may not be more than 6 digits # features/invalid_formats.feature:29
    Given I have a sort code 0899999                    # features/step_definitions/basics.rb:5
    And I have an account number 66374958               # features/step_definitions/basics.rb:9
    Then the combination is invalid                     # features/step_definitions/basics.rb:21

Feature: Modulus 10 Checking

  Background:                    # features/modulus10.feature:3
    Given I create a new checker # features/step_definitions/basics.rb:1

  Scenario: 1) Pass modulus 10 check      # features/modulus10.feature:6
    Given I have a sort code 089999       # features/step_definitions/basics.rb:5
    And I have an account number 66374958 # features/step_definitions/basics.rb:9
    Then the modulus is MOD10             # features/step_definitions/basics.rb:13
      undefined method `modulus' for nil:NilClass (NoMethodError)
      ./features/step_definitions/basics.rb:14:in `/^the modulus is (\S+)$/'
      features/modulus10.feature:10:in `Then the modulus is MOD10'
    And the combination is valid          # features/step_definitions/basics.rb:17

  Scenario: 29) Fail modulus 10 check     # features/modulus10.feature:13
    Given I have a sort code 089999       # features/step_definitions/basics.rb:5
    And I have an account number 66374959 # features/step_definitions/basics.rb:9
    Then the modulus is MOD10             # features/step_definitions/basics.rb:13
      undefined method `modulus' for nil:NilClass (NoMethodError)
      ./features/step_definitions/basics.rb:14:in `/^the modulus is (\S+)$/'
      features/modulus10.feature:17:in `Then the modulus is MOD10'
    And the combination is invalid        # features/step_definitions/basics.rb:21

Feature: Modulus 11 Checking

  Background:                    # features/modulus11.feature:3
    Given I create a new checker # features/step_definitions/basics.rb:1

  Scenario: 2) Pass modulus 11 check      # features/modulus11.feature:6
    Given I have a sort code 107999       # features/step_definitions/basics.rb:5
    And I have an account number 88837491 # features/step_definitions/basics.rb:9
    Then the modulus is MOD11             # features/step_definitions/basics.rb:13
      undefined method `modulus' for nil:NilClass (NoMethodError)
      ./features/step_definitions/basics.rb:14:in `/^the modulus is (\S+)$/'
      features/modulus11.feature:10:in `Then the modulus is MOD11'
    And the combination is valid          # features/step_definitions/basics.rb:17

  Scenario: 30) Fail modulus 11 check     # features/modulus11.feature:13
    Given I have a sort code 107999       # features/step_definitions/basics.rb:5
    And I have an account number 88837493 # features/step_definitions/basics.rb:9

Feature: Modulus Weight

  Scenario: Reading Weights                     # features/modulus_weight.feature:3
    Given I have the following weight data:     # features/step_definitions/modulus_weight.rb:1
      """
      070116 070116 MOD11    0    0    7    6    5    8    9    4    5    6    7    8    9   -1  12
      """
    Then the weight's sort_code_start is 070116 # features/step_definitions/modulus_weight.rb:5
    And the weight's sort_code_end is 070116    # features/step_definitions/modulus_weight.rb:5
    And the weight's modulus is MOD11           # features/step_definitions/modulus_weight.rb:5
    And the weight's u is 0                     # features/step_definitions/modulus_weight.rb:5
    And the weight's v is 0                     # features/step_definitions/modulus_weight.rb:5
    And the weight's w is 7                     # features/step_definitions/modulus_weight.rb:5
    And the weight's x is 6                     # features/step_definitions/modulus_weight.rb:5
    And the weight's y is 5                     # features/step_definitions/modulus_weight.rb:5
    And the weight's z is 8                     # features/step_definitions/modulus_weight.rb:5
    And the weight's a is 9                     # features/step_definitions/modulus_weight.rb:5
    And the weight's b is 4                     # features/step_definitions/modulus_weight.rb:5
    And the weight's c is 5                     # features/step_definitions/modulus_weight.rb:5
    And the weight's d is 6                     # features/step_definitions/modulus_weight.rb:5
    And the weight's e is 7                     # features/step_definitions/modulus_weight.rb:5
    And the weight's f is 8                     # features/step_definitions/modulus_weight.rb:5
    And the weight's g is 9                     # features/step_definitions/modulus_weight.rb:5
    And the weight's h is -1                    # features/step_definitions/modulus_weight.rb:5
    And the weight's exception is 12            # features/step_definitions/modulus_weight.rb:5

Feature: Modulus Weight Table

  Scenario: Finding appropriate modulus weight                        # features/modulus_weights_table.feature:3
    Given I have a modulus weight table loaded from data/valacdos.txt # features/step_definitions/modulus_weights_table.rb:1
    Then the modulus for sort code 010004 is MOD11                    # features/step_definitions/modulus_weights_table.rb:7
      undefined method `modulus' for nil:NilClass (NoMethodError)
      ./features/step_definitions/modulus_weights_table.rb:8:in `/^the modulus for sort code (\d+) is (\S+)$/'
      features/modulus_weights_table.feature:6:in `Then the modulus for sort code 010004 is MOD11'
    And the modulus for sort code 010005 is MOD11                     # features/step_definitions/modulus_weights_table.rb:7
    And the modulus for sort code 016714 is MOD11                     # features/step_definitions/modulus_weights_table.rb:7
    And the modulus for sort code 016715 is MOD11                     # features/step_definitions/modulus_weights_table.rb:7

  Scenario: Sort code doesn't exist                                   # features/modulus_weights_table.feature:11
    Given I have a modulus weight table loaded from data/valacdos.txt # features/step_definitions/modulus_weights_table.rb:1
    Then the modulus for sort code 020000 cannot be found             # features/step_definitions/modulus_weights_table.rb:11

Feature: Two Modulus Checks

  Background:                    # features/two_modulus_check.feature:3
    Given I create a new checker # features/step_definitions/basics.rb:1

  Scenario Outline: Valid Codes                  # features/two_modulus_check.feature:6
    Given I have a sort code <sortcode>          # features/two_modulus_check.feature:7
    And I have an account number <accountnumber> # features/two_modulus_check.feature:8
    Then the combination is valid                # features/two_modulus_check.feature:10

    Examples:
      | test | description                                  | sortcode | accountnumber |
      | 3    | Pass modulus 11 and double alternate checks. | 202959   | 63748472      |

  Scenario Outline: Invalid Codes                # features/two_modulus_check.feature:16
    Given I have a sort code <sortcode>          # features/two_modulus_check.feature:17
    And I have an account number <accountnumber> # features/two_modulus_check.feature:18
    Then the combination is invalid              # features/two_modulus_check.feature:20

    Examples:
      | test | description                                            | sortcode | accountnumber |
      | 27   | Pass modulus 11 check and fail double alternate check. | 203099   | 66831036      |

      expected false
           got true
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basics.rb:22:in `/^the combination is invalid$/'
      features/two_modulus_check.feature:24:in `Then the combination is invalid'
      features/two_modulus_check.feature:20:in `Then the combination is invalid'
      | 28   | Fail modulus 11 check and pass double alternate check. | 203099   | 58716970      |

      expected false
           got true
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basics.rb:22:in `/^the combination is invalid$/'
      features/two_modulus_check.feature:25:in `Then the combination is invalid'
      features/two_modulus_check.feature:20:in `Then the combination is invalid'

Failing Scenarios:
cucumber features/exceptions.feature:46 # Scenario Outline: Invalid Codes, Examples (#1)
cucumber features/exceptions.feature:47 # Scenario Outline: Invalid Codes, Examples (#2)
cucumber features/exceptions.feature:48 # Scenario Outline: Invalid Codes, Examples (#3)
cucumber features/exceptions.feature:49 # Scenario Outline: Invalid Codes, Examples (#4)
cucumber features/modulus10.feature:6 # Scenario: 1) Pass modulus 10 check
cucumber features/modulus10.feature:13 # Scenario: 29) Fail modulus 10 check
cucumber features/modulus11.feature:6 # Scenario: 2) Pass modulus 11 check
cucumber features/modulus_weights_table.feature:3 # Scenario: Finding appropriate modulus weight
cucumber features/two_modulus_check.feature:24 # Scenario Outline: Invalid Codes, Examples (#1)
cucumber features/two_modulus_check.feature:25 # Scenario Outline: Invalid Codes, Examples (#2)

43 scenarios (10 failed, 33 passed)
188 steps (10 failed, 6 skipped, 172 passed)
0m0.335s
12:12:27 uk_account_validator ruby-2.3.0 master$
```

**Comment by henrik** [comment]
Ah, it seems to fail on Ruby 2.3.0. Passes on 2.2.2.

**Comment by ball-hayden** [comment]
I'm afraid I haven't tried running this under 2.3.0.
I'd welcome a pull request if you can work out what's going on though...

**Comment by henrik** [comment]
No worries. We ended up not using this lib for now, so I'm afraid I won't be able to spend time on a PR :/
